### ISSUE TITLE
TypeError: match() takes exactly 2 arguments (3 given)

### ISSUE THREAD

**Issue by kp625544** [garyelephant/pygrok#25]
Your example says: 
from pygrok import Grok
text = 'gary is male, 25 years old and weighs 68.5 kilograms'
pattern = '%{WORD:name} is %{WORD:gender}, %{NUMBER:age:int} years old and weighs %{NUMBER:weight:float} kilograms'
grok = Grok(pattern)
print grok.match(text, pattern)

##{'gender': 'male', 'age': 25, 'name': 'gary', 'weight': 68.5}

When I tried I get following error: 
>>> from pygrok import Grok
>>> text = 'gary is male, 25 years old and weighs 68.5 kilograms'
>>> pattern = '%{WORD:name} is %{WORD:gender}, %{NUMBER:age:int} years old and weighs %{NUMBER:weight:float} kilograms'
>>> grok = Grok(pattern)
>>> print grok.match(text, pattern)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: match() takes exactly 2 arguments (3 given)

**Comment by garyelephant** [comment]
I'm really sorry for this, there is a typo in the example, and I correct this:

```
# from
grok.match(text, pattern)

# to 
grok.match(text)
```
