### ISSUE TITLE
Parsing Speed 200x slower than regex

### ISSUE THREAD

**Issue by the-c0d3r** [garyelephant/pygrok#28]
I was incorporating pygrok in a project to parse blacklist ips. It is only about 0.5MB in total, only 2 or 3 files. It took 70 seconds to parse through each row in the files. I didn't realize it was due to the pygrok, so I did multi-threading on it. And the speed is still considerably slow. The files are on HDD, not SSD, but then again, 0.5 MB file, it shouldn't take that long no matter SSD or HDD. 

And now I replaced pygrok with my regex pattern and it loaded the records, parsed them, within 0.04 seconds. Why is the speed so different? I understand grok patterns are also running on regular expression patterns in the lower level. Is there anything I can do to help investigate this?

Just did a test with 2.2 MB, it took 200 seconds. The same files took 0.187 seconds in regex. Why the difference is so high?

Additional Info
Pattern : `%{IP:HOST} %{GREEDYDATA:DESC}`
The file excerpt:
```
46.55.xxx.197 Malicious Host
221.xxx.13.22 Malicious Host
222.xxx.190.71 Malicious Host
```

**Comment by the-c0d3r** [comment]
Just did a test with 2.2 MB, it took 200 seconds. The same files took 0.187 seconds in regex. Why the difference is so high?

**Comment by garyelephant** [comment]
Thanks, @the-c0d3r I'm trying to figure out the problem, this didn't happen in my case.

**Comment by mail3dexter** [comment]
I am also facing this problem wherein the pygrok is taking lot of time to parse. In my case here are the stats,
Lines: 12930000 (Generated in 60 seconds)
Time: 159.436660767 (Time taken to parse them)

This library is providing me 0.37x performance and hence lagging.

Are there any plans to solve this problem in near future? If not then I will have to fall back to re library which I haven't explored
