### ISSUE TITLE
Parsing patterns fails if LANG environment variables not set

### ISSUE THREAD

**Issue by ghost** [garyelephant/pygrok#33]
The file grok-patterns contains an `ä` character and pygrok will fail reading the file if the LANG environment variables are not set to something that can support it.
As the files are shipped with UTF-8 so the encoding should be enforced.

**Comment by garyelephant** [comment]
thanks @dmeloni-radarservices , merged it

**Comment by stefansjs** [comment]
Look like this has been on master for a long time. Any chance we can get a 1.1 release with this fix?
